//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTestClient.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.INetTestService")]
    public interface INetTestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/login", ReplyAction="http://tempuri.org/INetTestService/loginResponse")]
        string login(NetTestModel.UserClass user);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/login", ReplyAction="http://tempuri.org/INetTestService/loginResponse")]
        System.IAsyncResult Beginlogin(NetTestModel.UserClass user, System.AsyncCallback callback, object asyncState);
        
        string Endlogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/addTest", ReplyAction="http://tempuri.org/INetTestService/addTestResponse")]
        NetTestModel.TestClass addTest(NetTestModel.TestClass test);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/addTest", ReplyAction="http://tempuri.org/INetTestService/addTestResponse")]
        System.IAsyncResult BeginaddTest(NetTestModel.TestClass test, System.AsyncCallback callback, object asyncState);
        
        NetTestModel.TestClass EndaddTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/getTestDataTable", ReplyAction="http://tempuri.org/INetTestService/getTestDataTableResponse")]
        System.Data.DataTable getTestDataTable();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/getTestDataTable", ReplyAction="http://tempuri.org/INetTestService/getTestDataTableResponse")]
        System.IAsyncResult BegingetTestDataTable(System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable EndgetTestDataTable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/deleteTest", ReplyAction="http://tempuri.org/INetTestService/deleteTestResponse")]
        bool deleteTest(NetTestModel.TestClass test);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/deleteTest", ReplyAction="http://tempuri.org/INetTestService/deleteTestResponse")]
        System.IAsyncResult BegindeleteTest(NetTestModel.TestClass test, System.AsyncCallback callback, object asyncState);
        
        bool EnddeleteTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/deleteTestList", ReplyAction="http://tempuri.org/INetTestService/deleteTestListResponse")]
        bool deleteTestList(int[] IDS);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/deleteTestList", ReplyAction="http://tempuri.org/INetTestService/deleteTestListResponse")]
        System.IAsyncResult BegindeleteTestList(int[] IDS, System.AsyncCallback callback, object asyncState);
        
        bool EnddeleteTestList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/updateTest", ReplyAction="http://tempuri.org/INetTestService/updateTestResponse")]
        void updateTest(NetTestModel.TestClass test);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/updateTest", ReplyAction="http://tempuri.org/INetTestService/updateTestResponse")]
        System.IAsyncResult BeginupdateTest(NetTestModel.TestClass test, System.AsyncCallback callback, object asyncState);
        
        void EndupdateTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/updateTestList", ReplyAction="http://tempuri.org/INetTestService/updateTestListResponse")]
        void updateTestList(NetTestModel.TestClass[] tests);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/updateTestList", ReplyAction="http://tempuri.org/INetTestService/updateTestListResponse")]
        System.IAsyncResult BeginupdateTestList(NetTestModel.TestClass[] tests, System.AsyncCallback callback, object asyncState);
        
        void EndupdateTestList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/getUserTestDataTable", ReplyAction="http://tempuri.org/INetTestService/getUserTestDataTableResponse")]
        System.Data.DataTable getUserTestDataTable();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/getUserTestDataTable", ReplyAction="http://tempuri.org/INetTestService/getUserTestDataTableResponse")]
        System.IAsyncResult BegingetUserTestDataTable(System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable EndgetUserTestDataTable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/setUserMark", ReplyAction="http://tempuri.org/INetTestService/setUserMarkResponse")]
        int setUserMark(int mValue);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/setUserMark", ReplyAction="http://tempuri.org/INetTestService/setUserMarkResponse")]
        System.IAsyncResult BeginsetUserMark(int mValue, System.AsyncCallback callback, object asyncState);
        
        int EndsetUserMark(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/getMarkDataTable", ReplyAction="http://tempuri.org/INetTestService/getMarkDataTableResponse")]
        System.Data.DataTable getMarkDataTable();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/getMarkDataTable", ReplyAction="http://tempuri.org/INetTestService/getMarkDataTableResponse")]
        System.IAsyncResult BegingetMarkDataTable(System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable EndgetMarkDataTable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INetTestService/deleteMarkList", ReplyAction="http://tempuri.org/INetTestService/deleteMarkListResponse")]
        void deleteMarkList(int[] mID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INetTestService/deleteMarkList", ReplyAction="http://tempuri.org/INetTestService/deleteMarkListResponse")]
        System.IAsyncResult BegindeleteMarkList(int[] mID, System.AsyncCallback callback, object asyncState);
        
        void EnddeleteMarkList(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INetTestServiceChannel : NetTestClient.WCF.INetTestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public NetTestModel.TestClass Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((NetTestModel.TestClass)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getTestDataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getTestDataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteTestListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteTestListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getUserTestDataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getUserTestDataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class setUserMarkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public setUserMarkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getMarkDataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getMarkDataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NetTestServiceClient : System.ServiceModel.ClientBase<NetTestClient.WCF.INetTestService>, NetTestClient.WCF.INetTestService {
        
        private BeginOperationDelegate onBeginloginDelegate;
        
        private EndOperationDelegate onEndloginDelegate;
        
        private System.Threading.SendOrPostCallback onloginCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddTestDelegate;
        
        private EndOperationDelegate onEndaddTestDelegate;
        
        private System.Threading.SendOrPostCallback onaddTestCompletedDelegate;
        
        private BeginOperationDelegate onBegingetTestDataTableDelegate;
        
        private EndOperationDelegate onEndgetTestDataTableDelegate;
        
        private System.Threading.SendOrPostCallback ongetTestDataTableCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteTestDelegate;
        
        private EndOperationDelegate onEnddeleteTestDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteTestCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteTestListDelegate;
        
        private EndOperationDelegate onEnddeleteTestListDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteTestListCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateTestDelegate;
        
        private EndOperationDelegate onEndupdateTestDelegate;
        
        private System.Threading.SendOrPostCallback onupdateTestCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateTestListDelegate;
        
        private EndOperationDelegate onEndupdateTestListDelegate;
        
        private System.Threading.SendOrPostCallback onupdateTestListCompletedDelegate;
        
        private BeginOperationDelegate onBegingetUserTestDataTableDelegate;
        
        private EndOperationDelegate onEndgetUserTestDataTableDelegate;
        
        private System.Threading.SendOrPostCallback ongetUserTestDataTableCompletedDelegate;
        
        private BeginOperationDelegate onBeginsetUserMarkDelegate;
        
        private EndOperationDelegate onEndsetUserMarkDelegate;
        
        private System.Threading.SendOrPostCallback onsetUserMarkCompletedDelegate;
        
        private BeginOperationDelegate onBegingetMarkDataTableDelegate;
        
        private EndOperationDelegate onEndgetMarkDataTableDelegate;
        
        private System.Threading.SendOrPostCallback ongetMarkDataTableCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteMarkListDelegate;
        
        private EndOperationDelegate onEnddeleteMarkListDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteMarkListCompletedDelegate;
        
        public NetTestServiceClient() {
        }
        
        public NetTestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NetTestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetTestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NetTestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<loginCompletedEventArgs> loginCompleted;
        
        public event System.EventHandler<addTestCompletedEventArgs> addTestCompleted;
        
        public event System.EventHandler<getTestDataTableCompletedEventArgs> getTestDataTableCompleted;
        
        public event System.EventHandler<deleteTestCompletedEventArgs> deleteTestCompleted;
        
        public event System.EventHandler<deleteTestListCompletedEventArgs> deleteTestListCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> updateTestCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> updateTestListCompleted;
        
        public event System.EventHandler<getUserTestDataTableCompletedEventArgs> getUserTestDataTableCompleted;
        
        public event System.EventHandler<setUserMarkCompletedEventArgs> setUserMarkCompleted;
        
        public event System.EventHandler<getMarkDataTableCompletedEventArgs> getMarkDataTableCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> deleteMarkListCompleted;
        
        public string login(NetTestModel.UserClass user) {
            return base.Channel.login(user);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginlogin(NetTestModel.UserClass user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginlogin(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string Endlogin(System.IAsyncResult result) {
            return base.Channel.Endlogin(result);
        }
        
        private System.IAsyncResult OnBeginlogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NetTestModel.UserClass user = ((NetTestModel.UserClass)(inValues[0]));
            return this.Beginlogin(user, callback, asyncState);
        }
        
        private object[] OnEndlogin(System.IAsyncResult result) {
            string retVal = this.Endlogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnloginCompleted(object state) {
            if ((this.loginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.loginCompleted(this, new loginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void loginAsync(NetTestModel.UserClass user) {
            this.loginAsync(user, null);
        }
        
        public void loginAsync(NetTestModel.UserClass user, object userState) {
            if ((this.onBeginloginDelegate == null)) {
                this.onBeginloginDelegate = new BeginOperationDelegate(this.OnBeginlogin);
            }
            if ((this.onEndloginDelegate == null)) {
                this.onEndloginDelegate = new EndOperationDelegate(this.OnEndlogin);
            }
            if ((this.onloginCompletedDelegate == null)) {
                this.onloginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnloginCompleted);
            }
            base.InvokeAsync(this.onBeginloginDelegate, new object[] {
                        user}, this.onEndloginDelegate, this.onloginCompletedDelegate, userState);
        }
        
        public NetTestModel.TestClass addTest(NetTestModel.TestClass test) {
            return base.Channel.addTest(test);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginaddTest(NetTestModel.TestClass test, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddTest(test, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public NetTestModel.TestClass EndaddTest(System.IAsyncResult result) {
            return base.Channel.EndaddTest(result);
        }
        
        private System.IAsyncResult OnBeginaddTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NetTestModel.TestClass test = ((NetTestModel.TestClass)(inValues[0]));
            return this.BeginaddTest(test, callback, asyncState);
        }
        
        private object[] OnEndaddTest(System.IAsyncResult result) {
            NetTestModel.TestClass retVal = this.EndaddTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddTestCompleted(object state) {
            if ((this.addTestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addTestCompleted(this, new addTestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addTestAsync(NetTestModel.TestClass test) {
            this.addTestAsync(test, null);
        }
        
        public void addTestAsync(NetTestModel.TestClass test, object userState) {
            if ((this.onBeginaddTestDelegate == null)) {
                this.onBeginaddTestDelegate = new BeginOperationDelegate(this.OnBeginaddTest);
            }
            if ((this.onEndaddTestDelegate == null)) {
                this.onEndaddTestDelegate = new EndOperationDelegate(this.OnEndaddTest);
            }
            if ((this.onaddTestCompletedDelegate == null)) {
                this.onaddTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddTestCompleted);
            }
            base.InvokeAsync(this.onBeginaddTestDelegate, new object[] {
                        test}, this.onEndaddTestDelegate, this.onaddTestCompletedDelegate, userState);
        }
        
        public System.Data.DataTable getTestDataTable() {
            return base.Channel.getTestDataTable();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetTestDataTable(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetTestDataTable(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable EndgetTestDataTable(System.IAsyncResult result) {
            return base.Channel.EndgetTestDataTable(result);
        }
        
        private System.IAsyncResult OnBegingetTestDataTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetTestDataTable(callback, asyncState);
        }
        
        private object[] OnEndgetTestDataTable(System.IAsyncResult result) {
            System.Data.DataTable retVal = this.EndgetTestDataTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetTestDataTableCompleted(object state) {
            if ((this.getTestDataTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getTestDataTableCompleted(this, new getTestDataTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getTestDataTableAsync() {
            this.getTestDataTableAsync(null);
        }
        
        public void getTestDataTableAsync(object userState) {
            if ((this.onBegingetTestDataTableDelegate == null)) {
                this.onBegingetTestDataTableDelegate = new BeginOperationDelegate(this.OnBegingetTestDataTable);
            }
            if ((this.onEndgetTestDataTableDelegate == null)) {
                this.onEndgetTestDataTableDelegate = new EndOperationDelegate(this.OnEndgetTestDataTable);
            }
            if ((this.ongetTestDataTableCompletedDelegate == null)) {
                this.ongetTestDataTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetTestDataTableCompleted);
            }
            base.InvokeAsync(this.onBegingetTestDataTableDelegate, null, this.onEndgetTestDataTableDelegate, this.ongetTestDataTableCompletedDelegate, userState);
        }
        
        public bool deleteTest(NetTestModel.TestClass test) {
            return base.Channel.deleteTest(test);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindeleteTest(NetTestModel.TestClass test, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindeleteTest(test, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EnddeleteTest(System.IAsyncResult result) {
            return base.Channel.EnddeleteTest(result);
        }
        
        private System.IAsyncResult OnBegindeleteTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NetTestModel.TestClass test = ((NetTestModel.TestClass)(inValues[0]));
            return this.BegindeleteTest(test, callback, asyncState);
        }
        
        private object[] OnEnddeleteTest(System.IAsyncResult result) {
            bool retVal = this.EnddeleteTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteTestCompleted(object state) {
            if ((this.deleteTestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteTestCompleted(this, new deleteTestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteTestAsync(NetTestModel.TestClass test) {
            this.deleteTestAsync(test, null);
        }
        
        public void deleteTestAsync(NetTestModel.TestClass test, object userState) {
            if ((this.onBegindeleteTestDelegate == null)) {
                this.onBegindeleteTestDelegate = new BeginOperationDelegate(this.OnBegindeleteTest);
            }
            if ((this.onEnddeleteTestDelegate == null)) {
                this.onEnddeleteTestDelegate = new EndOperationDelegate(this.OnEnddeleteTest);
            }
            if ((this.ondeleteTestCompletedDelegate == null)) {
                this.ondeleteTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteTestCompleted);
            }
            base.InvokeAsync(this.onBegindeleteTestDelegate, new object[] {
                        test}, this.onEnddeleteTestDelegate, this.ondeleteTestCompletedDelegate, userState);
        }
        
        public bool deleteTestList(int[] IDS) {
            return base.Channel.deleteTestList(IDS);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindeleteTestList(int[] IDS, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindeleteTestList(IDS, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EnddeleteTestList(System.IAsyncResult result) {
            return base.Channel.EnddeleteTestList(result);
        }
        
        private System.IAsyncResult OnBegindeleteTestList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int[] IDS = ((int[])(inValues[0]));
            return this.BegindeleteTestList(IDS, callback, asyncState);
        }
        
        private object[] OnEnddeleteTestList(System.IAsyncResult result) {
            bool retVal = this.EnddeleteTestList(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteTestListCompleted(object state) {
            if ((this.deleteTestListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteTestListCompleted(this, new deleteTestListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteTestListAsync(int[] IDS) {
            this.deleteTestListAsync(IDS, null);
        }
        
        public void deleteTestListAsync(int[] IDS, object userState) {
            if ((this.onBegindeleteTestListDelegate == null)) {
                this.onBegindeleteTestListDelegate = new BeginOperationDelegate(this.OnBegindeleteTestList);
            }
            if ((this.onEnddeleteTestListDelegate == null)) {
                this.onEnddeleteTestListDelegate = new EndOperationDelegate(this.OnEnddeleteTestList);
            }
            if ((this.ondeleteTestListCompletedDelegate == null)) {
                this.ondeleteTestListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteTestListCompleted);
            }
            base.InvokeAsync(this.onBegindeleteTestListDelegate, new object[] {
                        IDS}, this.onEnddeleteTestListDelegate, this.ondeleteTestListCompletedDelegate, userState);
        }
        
        public void updateTest(NetTestModel.TestClass test) {
            base.Channel.updateTest(test);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateTest(NetTestModel.TestClass test, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateTest(test, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndupdateTest(System.IAsyncResult result) {
            base.Channel.EndupdateTest(result);
        }
        
        private System.IAsyncResult OnBeginupdateTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NetTestModel.TestClass test = ((NetTestModel.TestClass)(inValues[0]));
            return this.BeginupdateTest(test, callback, asyncState);
        }
        
        private object[] OnEndupdateTest(System.IAsyncResult result) {
            this.EndupdateTest(result);
            return null;
        }
        
        private void OnupdateTestCompleted(object state) {
            if ((this.updateTestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateTestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateTestAsync(NetTestModel.TestClass test) {
            this.updateTestAsync(test, null);
        }
        
        public void updateTestAsync(NetTestModel.TestClass test, object userState) {
            if ((this.onBeginupdateTestDelegate == null)) {
                this.onBeginupdateTestDelegate = new BeginOperationDelegate(this.OnBeginupdateTest);
            }
            if ((this.onEndupdateTestDelegate == null)) {
                this.onEndupdateTestDelegate = new EndOperationDelegate(this.OnEndupdateTest);
            }
            if ((this.onupdateTestCompletedDelegate == null)) {
                this.onupdateTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateTestCompleted);
            }
            base.InvokeAsync(this.onBeginupdateTestDelegate, new object[] {
                        test}, this.onEndupdateTestDelegate, this.onupdateTestCompletedDelegate, userState);
        }
        
        public void updateTestList(NetTestModel.TestClass[] tests) {
            base.Channel.updateTestList(tests);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateTestList(NetTestModel.TestClass[] tests, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateTestList(tests, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndupdateTestList(System.IAsyncResult result) {
            base.Channel.EndupdateTestList(result);
        }
        
        private System.IAsyncResult OnBeginupdateTestList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NetTestModel.TestClass[] tests = ((NetTestModel.TestClass[])(inValues[0]));
            return this.BeginupdateTestList(tests, callback, asyncState);
        }
        
        private object[] OnEndupdateTestList(System.IAsyncResult result) {
            this.EndupdateTestList(result);
            return null;
        }
        
        private void OnupdateTestListCompleted(object state) {
            if ((this.updateTestListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateTestListCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateTestListAsync(NetTestModel.TestClass[] tests) {
            this.updateTestListAsync(tests, null);
        }
        
        public void updateTestListAsync(NetTestModel.TestClass[] tests, object userState) {
            if ((this.onBeginupdateTestListDelegate == null)) {
                this.onBeginupdateTestListDelegate = new BeginOperationDelegate(this.OnBeginupdateTestList);
            }
            if ((this.onEndupdateTestListDelegate == null)) {
                this.onEndupdateTestListDelegate = new EndOperationDelegate(this.OnEndupdateTestList);
            }
            if ((this.onupdateTestListCompletedDelegate == null)) {
                this.onupdateTestListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateTestListCompleted);
            }
            base.InvokeAsync(this.onBeginupdateTestListDelegate, new object[] {
                        tests}, this.onEndupdateTestListDelegate, this.onupdateTestListCompletedDelegate, userState);
        }
        
        public System.Data.DataTable getUserTestDataTable() {
            return base.Channel.getUserTestDataTable();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetUserTestDataTable(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetUserTestDataTable(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable EndgetUserTestDataTable(System.IAsyncResult result) {
            return base.Channel.EndgetUserTestDataTable(result);
        }
        
        private System.IAsyncResult OnBegingetUserTestDataTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetUserTestDataTable(callback, asyncState);
        }
        
        private object[] OnEndgetUserTestDataTable(System.IAsyncResult result) {
            System.Data.DataTable retVal = this.EndgetUserTestDataTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetUserTestDataTableCompleted(object state) {
            if ((this.getUserTestDataTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getUserTestDataTableCompleted(this, new getUserTestDataTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getUserTestDataTableAsync() {
            this.getUserTestDataTableAsync(null);
        }
        
        public void getUserTestDataTableAsync(object userState) {
            if ((this.onBegingetUserTestDataTableDelegate == null)) {
                this.onBegingetUserTestDataTableDelegate = new BeginOperationDelegate(this.OnBegingetUserTestDataTable);
            }
            if ((this.onEndgetUserTestDataTableDelegate == null)) {
                this.onEndgetUserTestDataTableDelegate = new EndOperationDelegate(this.OnEndgetUserTestDataTable);
            }
            if ((this.ongetUserTestDataTableCompletedDelegate == null)) {
                this.ongetUserTestDataTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetUserTestDataTableCompleted);
            }
            base.InvokeAsync(this.onBegingetUserTestDataTableDelegate, null, this.onEndgetUserTestDataTableDelegate, this.ongetUserTestDataTableCompletedDelegate, userState);
        }
        
        public int setUserMark(int mValue) {
            return base.Channel.setUserMark(mValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginsetUserMark(int mValue, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginsetUserMark(mValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndsetUserMark(System.IAsyncResult result) {
            return base.Channel.EndsetUserMark(result);
        }
        
        private System.IAsyncResult OnBeginsetUserMark(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int mValue = ((int)(inValues[0]));
            return this.BeginsetUserMark(mValue, callback, asyncState);
        }
        
        private object[] OnEndsetUserMark(System.IAsyncResult result) {
            int retVal = this.EndsetUserMark(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsetUserMarkCompleted(object state) {
            if ((this.setUserMarkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.setUserMarkCompleted(this, new setUserMarkCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void setUserMarkAsync(int mValue) {
            this.setUserMarkAsync(mValue, null);
        }
        
        public void setUserMarkAsync(int mValue, object userState) {
            if ((this.onBeginsetUserMarkDelegate == null)) {
                this.onBeginsetUserMarkDelegate = new BeginOperationDelegate(this.OnBeginsetUserMark);
            }
            if ((this.onEndsetUserMarkDelegate == null)) {
                this.onEndsetUserMarkDelegate = new EndOperationDelegate(this.OnEndsetUserMark);
            }
            if ((this.onsetUserMarkCompletedDelegate == null)) {
                this.onsetUserMarkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsetUserMarkCompleted);
            }
            base.InvokeAsync(this.onBeginsetUserMarkDelegate, new object[] {
                        mValue}, this.onEndsetUserMarkDelegate, this.onsetUserMarkCompletedDelegate, userState);
        }
        
        public System.Data.DataTable getMarkDataTable() {
            return base.Channel.getMarkDataTable();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetMarkDataTable(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetMarkDataTable(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable EndgetMarkDataTable(System.IAsyncResult result) {
            return base.Channel.EndgetMarkDataTable(result);
        }
        
        private System.IAsyncResult OnBegingetMarkDataTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetMarkDataTable(callback, asyncState);
        }
        
        private object[] OnEndgetMarkDataTable(System.IAsyncResult result) {
            System.Data.DataTable retVal = this.EndgetMarkDataTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetMarkDataTableCompleted(object state) {
            if ((this.getMarkDataTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getMarkDataTableCompleted(this, new getMarkDataTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getMarkDataTableAsync() {
            this.getMarkDataTableAsync(null);
        }
        
        public void getMarkDataTableAsync(object userState) {
            if ((this.onBegingetMarkDataTableDelegate == null)) {
                this.onBegingetMarkDataTableDelegate = new BeginOperationDelegate(this.OnBegingetMarkDataTable);
            }
            if ((this.onEndgetMarkDataTableDelegate == null)) {
                this.onEndgetMarkDataTableDelegate = new EndOperationDelegate(this.OnEndgetMarkDataTable);
            }
            if ((this.ongetMarkDataTableCompletedDelegate == null)) {
                this.ongetMarkDataTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetMarkDataTableCompleted);
            }
            base.InvokeAsync(this.onBegingetMarkDataTableDelegate, null, this.onEndgetMarkDataTableDelegate, this.ongetMarkDataTableCompletedDelegate, userState);
        }
        
        public void deleteMarkList(int[] mID) {
            base.Channel.deleteMarkList(mID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindeleteMarkList(int[] mID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindeleteMarkList(mID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EnddeleteMarkList(System.IAsyncResult result) {
            base.Channel.EnddeleteMarkList(result);
        }
        
        private System.IAsyncResult OnBegindeleteMarkList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int[] mID = ((int[])(inValues[0]));
            return this.BegindeleteMarkList(mID, callback, asyncState);
        }
        
        private object[] OnEnddeleteMarkList(System.IAsyncResult result) {
            this.EnddeleteMarkList(result);
            return null;
        }
        
        private void OndeleteMarkListCompleted(object state) {
            if ((this.deleteMarkListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteMarkListCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteMarkListAsync(int[] mID) {
            this.deleteMarkListAsync(mID, null);
        }
        
        public void deleteMarkListAsync(int[] mID, object userState) {
            if ((this.onBegindeleteMarkListDelegate == null)) {
                this.onBegindeleteMarkListDelegate = new BeginOperationDelegate(this.OnBegindeleteMarkList);
            }
            if ((this.onEnddeleteMarkListDelegate == null)) {
                this.onEnddeleteMarkListDelegate = new EndOperationDelegate(this.OnEnddeleteMarkList);
            }
            if ((this.ondeleteMarkListCompletedDelegate == null)) {
                this.ondeleteMarkListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteMarkListCompleted);
            }
            base.InvokeAsync(this.onBegindeleteMarkListDelegate, new object[] {
                        mID}, this.onEnddeleteMarkListDelegate, this.ondeleteMarkListCompletedDelegate, userState);
        }
    }
}
